/*
 *
 * PlacesPage constants
 *
 */

export const PLACES_REQUEST = 'PLACES_REQUEST';
export const PLACES_ERROR = 'PLACES_ERROR';
export const PLACES_SUCCESS = 'PLACES_SUCCESS';

export const DETAIL_REQUEST = 'DETAIL_REQUEST';
export const DETAIL_ERROR = 'DETAIL_ERROR';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';

export const INC_SELECTED_INDEX = 'INC_SELECTED_INDEX';
export const DEC_SELECTED_INDEX = 'DEC_SELECTED_INDEX';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
