/*
 *
 * AutoComplete constants
 *
 */

export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_ERROR   = 'AUTOCOMPLETE_ERROR';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_ITEM_SELECTED = 'AUTOCOMPLETE_ITEM_SELECTED';
