/**
 * Created by Joey on 9/22/2016.
 */

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_ERROR   = 'USER_LOCATION_ERROR';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';

export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_ERROR   = 'AUTOCOMPLETE_ERROR';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';

export const PLACES_REQUEST = 'PLACES_REQUEST';
export const PLACES_ERROR = 'PLACES_ERROR';
export const PLACES_SUCCESS = 'PLACES_SUCCESS';

export const PLACE_DETAILS_REQUEST = 'PLACE_DETAILS_REQUEST';
export const PLACE_DETAILS_ERROR = 'PLACE_DETAILS_ERROR';
export const PLACE_DETAILS_SUCCESS = 'PLACE_DETAILS_SUCCESS';

export const DISTANCE_MATRIX_REQUEST = 'PLACE_DISTANCE_REQUEST';
export const DISTANCE_MATRIX_SUCCESS = 'DISTANCE_MATRIX_SUCCESS';
export const DISTANCE_MATRIX_ERROR = 'DISTANCE_MATRIX_ERROR';

