/**
 * Created by Joey on 9/22/2016.
 */

export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_ERROR   = 'AUTOCOMPLETE_ERROR';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_ITEM_SELECTED = 'AUTOCOMPLETE_ITEM_SELECTED';

export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';

export const NOODLE_TIME = 'NOODLE_TIME';



