/**
 * Created by Joey on 9/22/2016.
 */

export const FETCH_USER_LOCATION = 'FETCH_USER_LOCATION';
export const USER_LOCATION_PENDING = 'USER_LOCATION_PENDING';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';
export const USER_LOCATION_FOUND = 'USER_LOCATION_FOUND';