/**
 * Created by Joey on 12/12/2016.
 */

export const USER_HAS_GEO = 'USER_HAS_GEO';

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';

export const GEOCODE_REQUEST = 'GEOCODE_REQUEST';
